### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by takuya4520** [takuya4520/aicon-app#28]
### 実装予定の機能
* [ ] ユーザー登録
* [ ] ログイン/ログイアウト
* [ ] パスワードリセット
* [ ] マイページ設定 / 編集
* [ ] アイコン生成 / 削除
* [ ] アイコン投稿 / 編集 / 削除
* [ ] アイコン一覧
* [ ] アイコンいいね機能 / 一覧
* [ ] X（旧Twitter）シェア機能
* [ ] ソート機能

### 必要なページ
* [ ] トップページ
* [ ] ログインページ
* [ ] ユーザー登録ページ
* [ ] パスワードリセットページ
* [ ] ログイン後トップページ
* [ ] アイコン生成ページ
* [ ] アイコン生成後ページ
* [ ] アイコン投稿ページ
* [ ] アイコン一覧ページ
* [ ] アイコン詳細ページ
* [ ] アイコン編集ページ
* [ ] マイページ
* [ ] マイページ編集ページ
* [ ] いいねしたアイコン一覧ページ

**Comment by Tsuchiya2** [comment]
ご提出ありがとうございます。
ストーリーポイント5のissueは、おそらくまだ見通しが立たないことからの数値と見受けました。
ストーリーポイント5のissueをもう少し細かく分解(1, 2くらいレベルまで)しましょう。

**Comment by takuya4520** [comment]
[Tsuchiya2](https://github.com/Tsuchiya2)講師
ご確認いただきありがとうございます。

ご指摘のとおりまだ見通しが立たない箇所ではありましたが、もう少し細かく分解させて頂きました。

再度ご確認のほどよろしくお願いいたします。

**Comment by tmtkzk0823** [comment]
修正ありがとうございます。
以下コメントになります。

- [#7](https://github.com/takuya4520/graduation_exam/issues/7)
こちらのissueですが、新規登録機能とログイン機能は別のissueで管理する方がいいかと思いました。

**Comment by takuya4520** [comment]
[tmtkzk0823](https://github.com/tmtkzk0823)講師
ご確認いただきありがとうございます！

新規登録機能とログイン / ログアウト機能は別のissueで管理するように変更させて頂きました。

再度ご確認のほどよろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。
