### ISSUE TITLE
MVPリリース　レビュー依頼

### ISSUE THREAD

**Issue by takuya4520** [takuya4520/aicon-app#96]
いつも大変お世話になっております。
卒業試験のMVPリリースレビュー依頼を提出いたします。

## 各種情報
サービス名：A.Icon(ええアイコン）
サービスURL：https://www.aicon-app.com/

### 実装予定の機能
* [x] ユーザー登録
* [x] ログイン/ログイアウト
* [x] パスワードリセット
* [x] マイページ設定 / 編集
* [x] アイコン生成 / 削除
* [x] アイコン投稿 / 編集 / 削除
* [x] アイコン一覧
* [x] アイコンいいね機能 / 一覧
* [x] X（旧Twitter）シェア機能
* [x] ソート機能

## READMEレビュー時から追加した機能
* [x] ゲストログイン機能
* [x] 公開/非公開設定機能

## 本リリース時に実装したい機能
* [ ]  X（旧Twitter）シェア時の画像表示機能
* [ ] 管理者機能
* [ ] NGワードバリデーション機能

## サービスイメージがわかるようなスクリーンショット等
管理画面等はございません。
#### トップページ：
<img width="1003" alt="スクリーンショット 2024-03-20 10 55 46" src="https://github.com/takuya4520/iconya-app/assets/108344446/20f3da93-7d71-4caa-8277-7646ccb306ee">

#### アイコン一覧ページ：
<img width="995" alt="スクリーンショット 2024-03-20 10 54 59" src="https://github.com/takuya4520/iconya-app/assets/108344446/380f6371-7497-417c-bb9b-cbe7991066a5">

#### アイコン生成ページ：
<img width="466" alt="スクリーンショット 2024-03-20 10 54 22" src="https://github.com/takuya4520/iconya-app/assets/108344446/ba15e9a2-96ad-47f5-b5e2-18285e188a8d">

#### アイコンの保存(投稿)ページ
<img width="471" alt="スクリーンショット 2024-03-20 10 54 41" src="https://github.com/takuya4520/iconya-app/assets/108344446/d7e7283d-fe23-4fe3-ab98-ce0dcd950469">

#### アイコン詳細ページ:
<img width="704" alt="スクリーンショット 2024-03-20 11 06 15" src="https://github.com/takuya4520/iconya-app/assets/108344446/dbdcb231-c1e3-4e24-85ee-a4df15147df0">

#### マイページ:
<img width="994" alt="スクリーンショット 2024-03-20 10 55 24" src="https://github.com/takuya4520/iconya-app/assets/108344446/4514e8c0-41f1-47ad-a439-ce51eec5048c">

#### お気に入りのアイコンページ
<img width="816" alt="スクリーンショット 2024-03-20 10 55 11" src="https://github.com/takuya4520/iconya-app/assets/108344446/f7c9e34e-61d2-4272-86e3-4d0430b0d8dc">

以上、ご確認のほどよろしくお願いいたします。

**Comment by kenchasonakai** [comment]
LGTMです！
